services:
  deepsel-cms-backend:
    build: .
    container_name: deepsel-cms-backend
    depends_on:
      - deepsel-cms-db
    env_file:
      - .env
    environment:
      DB_HOST: deepsel-cms-db
    volumes:
      - ./volumes/files:/usr/src/app/files

  deepsel-cms-db:
    image: postgres:17.4-alpine3.21
    container_name: deepsel-cms-db
    ports:
      - 5432:5432
    volumes:
      # - ./volumes/pg_data:/var/lib/postgresql/data
      - ./volumes/pg_data2:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}